### PR TITLE
Test route fix

### PR DESCRIPTION
**Pull request by prateekjadhwani**
This is how i am adding stuff to make "test" route work.

### CODE REVIEW

**Comment by processnotproduct** [comment]
This actually isn't working right. It doesn't go to the test section of the home.html page.

**Comment by prateekjadhwani** [comment]
It seems i forgot to update the url in the index file. I will create another pull reqest

**Comment by processnotproduct** [comment]
It seems to be routing there now but it doesn't go to that location on the page and every page is the same height as the longest one.

**Comment by prateekjadhwani** [comment]
Yes, i did not fix the layout issues. Only worked on routing.
I thought that might have been blocking you from working on.

**Pull request merged**
